[package]
name = "bmath"
version = "0.1.0"
edition = "2018"
authors = ["Andrew Thompson"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
num = "0.4"